variable "env" {}
variable "tags" {}
variable "vpc_id" {}
variable "sg_subnets_cidr" {}
variable "component" {}
variable "instance_type" {}
variable "kms_key_id" {}
variable "desired_capacity" {}
variable "max_size" {}
variable "min_size" {}
variable "subnets" {}
variable "app_port" {}
variable "allow_ssh_cidr" {}